# Generated by Django 4.0.4 on 2022-06-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_remove_menuitem_link_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='page',
        ),
    ]
