# Generated by Django 4.0.4 on 2022-06-01 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('menus', '0012_alter_menu_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='menus.menuitem'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('translation_key', 'locale')},
        ),
    ]
