# Generated by Django 4.0.4 on 2022-06-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0022_menu_locale_menu_translation_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='translation_key',
        ),

    ]

